/**
 * dsh-model-live — Client 构建脚本（零依赖）
 *
 * 产物契约（DSH client-modules）：
 *   window.__ModuleLoader__.load({ id: "<包名>", factory: (require) => module.exports })
 * - classic <script> 加载；factory 是 CJS 闭包，接收运行时 require
 * - react 由运行时 seed，外部化（不打包）
 *
 * 客户端源码是纯 JS（无 JSX / 无 import），所以这里只套一层装载外壳：
 *   node client/build.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkgName = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).name
const src = readFileSync(join(root, 'client', 'index.js'), 'utf8')
const outDir = join(root, 'client', 'dist')
const outFile = join(outDir, 'index.js')

const banner = `/* ${pkgName} client bundle — generated by client/build.mjs */
window.__ModuleLoader__.load({
\tid: ${JSON.stringify(pkgName)},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
`
const footer = `
\t\treturn module.exports;
\t}
});
`

mkdirSync(outDir, { recursive: true })
writeFileSync(outFile, banner + src + footer, 'utf8')
console.log('built:', outFile, 'bytes:', (banner + src + footer).length)
